### ISSUE TITLE
deploy on openshift

### ISSUE THREAD

**Issue by bikej** [punkstar/docker-o-saft#1]
Hi,  I have set up openshift origin environment and wanted to deploy o-saft.
This is what I get after deploying image.

Crash Loop Back-off 

oc log po/o-saft-1-42gpz

=== reading: ./.o-saft.pl (RC-FILE done) ===
=== reading: /usr/local/share/perl/5.22.1/IO/Socket/SSL.pm (IO SSL module done) ===
=== reading: /opt/osaft/Net/SSLinfo.pm (O-Saft module done) ===
  o-saft.pl +info   your.tld
  o-saft.pl +check  your.tld
  o-saft.pl +cipher your.tld
  o-saft.pl --help

What do I have to do?

**Comment by punkstar** [comment]
I'm afraid I don't have any experience with openshift origin. I recommend you take a look at https://github.com/OWASP/O-Saft, they have an official docker image now.
